### PR TITLE
added dark mode

### LINKED ISSUE #2: Dark Mode
**Is your feature request related to a problem? Please describe.**
For accessibility reasons (and not just because dark mode is epic), we must have a dark mode.
**Describe the solution you'd like**
We need a way for the user to toggle it, so we should discuss on where we should keep this setting?

**Describe alternatives you've considered**
None.

### PR DESCRIPTION
**Pull request by markverb1**
**Resolves**

Resolves #2 

**Changes**

Added dark mode.

**Tests**

Tested locally, because from now on I won't use replit for development.

also, you may have noticed that I removed alot of stuff where you wouldn't expect me to. this is just because I formated those files with VS Code

### CODE REVIEW

**Comment by TheColaber** [comment]
I would actually like to do this will css variables rather than doing !important and having a ton of css selectors

**Comment by markverb1** [comment]
> I would actually like to do this will css variables rather than doing !important and having a ton of css selectors

i think i only put like 1 `!important` rule

**Comment by TheColaber** [comment]
Pls use css variables

**Comment by markverb1** [comment]
> Pls use css variables

how

**Comment by TheColaber** [comment]
Look up dark mode like with css variables

**Comment by markverb1** [comment]
okay ill make a new pr when i get dark mode with css vars working

**Pull request closed without merging**
