### PR TITLE
Add Nuxt

### LINKED ISSUE #57: Nuxtify
Nuxify.

jeffalo might not be helping much on this part, but definitely, I will try to learn some nuxt stuff and create a separate repo for this as FlagClick2.0... but won't be until we have a v1.0...

### LINKED ISSUE #86: blog
blog/announcements thing

### PR DESCRIPTION
**Pull request by TheColaber**
Resolves #57
Resolves #86

### CODE REVIEW

**Comment by TheColaber** [comment]
The goal is to at least match/exceed the current master state.

Btw @FunctionalMetatable try searching WhenFlagClicked on google. It's pretty high up don't you think :)

**Comment by TheColaber** [comment]
I'm noticing a problem with the markdown, hmm. Try going to http://localhost:3000/blog/md-tutorial. Also, try making a new tutorial and creating code.

**Comment by FunctionalMetatable** [comment]
> I'm noticing a problem with the markdown, hmm. Try going to http://localhost:3000/blog/md-tutorial. Also, try making a new tutorial and creating code.

fixed



> Although apparently searching "when flag clicked" gives different results :P

including an instagram account for some reason lol

**Comment by FunctionalMetatable** [comment]
I've deployed it to replit
Preview: https://flagclicked-2.9gr.repl.co/

**Comment by FunctionalMetatable** [comment]
I'd like to note this:
When we use axios, we have to use a baseURL param. This is defaulting to localhost:3000 which makes all requests go to localhost:3000 instead of the proper base URL.
I think we should write a plugin for axios instead of using the default @nuxtjs/axios

**Review by FunctionalMetatable — APPROVED** [review]
LGTM for now

**Comment by TheColaber** [comment]
I'm guessing axios was fixed?

**Comment by CubeyTheCube** [comment]
this period annoys me
image
these buttons suck
image
I don't think the auth page should be a studio page since the studio page hurts my eyes
It should be a project instead
(Also, it logged me out after I logged in. I had to log in twice, which was annoying).

The tutorial page is great but the pfp is too far to the left
image
The buttons in the header need more padding as well.

Code wise, it LGTM.

**Comment by markverb1** [comment]
Suggestions:
add this css to the buttons:
image
make the editor be atleast 300px
Bugs:
This:
image

**Comment by TheColaber** [comment]
@FunctionalMetatable your prettier settings are making it hard to read commits :(

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable your prettier settings are making it hard to read commits :(

I should globally install prettier

anyways everything from cubey and markverb1s suggestions are done except navbar padding

**Comment by TheColaber** [comment]
Oh, yeah. We need to hide the my tutorials and new tutorials button in the navbar when the user is logged out and replace it with maybe the about page

**Comment by TheColaber** [comment]
Let's also support a bit of mobile since, non nuxt had it, and it's really bad right now

**Comment by TheColaber** [comment]
Let's cleanup the footer a bit too. Let's fix the when flag clicked block and add GitHub repo there too. Let's remove the tutorials link there too.

**Comment by TheColaber** [comment]
Let's hide "this week's featured tutorials when there is none. Contact us page needs a wip page for now. Let's fix scratch-blocks issues . Oh and we should add the credits page to the footer.

**Comment by TheColaber** [comment]
@FunctionalMetatable Whats going on with the z-index... is it doing anything, I can't tell.

**Comment by TheColaber** [comment]
@FunctionalMetatable I want to merge this after I address this problem:
image
Any idea why this is happening? This error is flooding terminals.

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable I want to merge this after I address this problem:
> image
> Any idea why this is happening? This error is flooding terminals.

normal with nuxt: babel made this happen and I did a bit of research few days ago and next release will fix this

**Comment by FunctionalMetatable** [comment]
rip the old https://www.whenflagclicked.org/

**Comment by TheColaber** [comment]
I disconnected it from replit, why is it still on a replit screen

**Comment by FunctionalMetatable** [comment]
> I disconnected it from replit, why is it still on a replit screen

the domain is still linked to replit; you just deleted the repl i think

**Review by FunctionalMetatable — COMMENTED** [review]
lgtm code-wise
tested locally and no errors present but:
1 error only: featured endpoint doesnt work correctly :/

**Comment by TheColaber** [comment]
Why does it not work?

**Comment by TheColaber** [comment]
I haven't tested admin yet, I need to clear the database somehow

**Comment by FunctionalMetatable** [comment]
> I haven't tested admin yet, I need to clear the database somehow

just put this in server-middleware/server.js right before `export default app`:
```js
auth.databases.users.update({ username: "TheColaber" }, { $set: { admin: true } })
```

**Comment by TheColaber** [comment]
I'm currently waiting for Fosshost's applications to be unsuspended...
image
If only I was 2 days faster, now I have to wait 2 weeks later :(

Anyway, lets merge this thing

**Pull request merged**
